# Generated by Django 4.2.3 on 2023-08-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
