# Generated by Django 4.2.3 on 2023-08-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
