# Generated by Django 3.2.7 on 2023-09-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_favorite',
        ),
    ]
