# Generated by Django 4.2.3 on 2023-09-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_uploaded',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
