# Generated by Django 4.2.3 on 2023-09-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_uploaded',
            new_name='alarm_status',
        ),
    ]
