# Generated by Django 3.2.7 on 2023-10-01 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20231001_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ProductProfile',
            name='user_id',
        ),
    ]
