# Generated by Django 4.2.3 on 2023-08-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_email_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_url',
            field=models.URLField(default=''),
        ),
    ]
