# Generated by Django 4.2.3 on 2023-08-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
