# syntax=docker/dockerfile:1

FROM python:3.9-buster
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /apps
COPY apps /apps/

EXPOSE 8000/tcp

RUN chmod +x /apps/entrypoint.celery.sh
CMD /apps/entrypoint.celery.sh